/**
 * Shared institutional print/PDF layout for SMS Oriximiná.
 * All documents generated by the system use this template
 * to ensure consistent branding across screen, PDF, and print.
 * 
 * Supports dual logos (SMS + CAPS II), justified text, proper
 * margins (A4), Arial font.
 */

import { supabase } from '@/integrations/supabase/client';
import logoSmsFallback from '@/assets/logo-sms-oriximina.jpeg';
import logoCapsFallback from '@/assets/logo-caps-ii.png';

export interface DocumentConfig {
  logoEsquerda: string;
  logoCentro: string;
  logoDireita: string;
  logoEsquerdaTamanho: number;
  logoCentroTamanho: number;
  logoDireitaTamanho: number;
  logoEsquerdaAtiva: boolean;
  logoCentroAtiva: boolean;
  logoDireitaAtiva: boolean;
  logoEsquerdaRedonda: boolean;
  logoCentroRedonda: boolean;
  logoDireitaRedonda: boolean;
  linha1: string;
  linha2: string;
  rodapeTexto: string;
  fonte: string;
  tamanhoFonte: number;
  alinhamento: 'left' | 'center' | 'right';
  corTitulo: string;
}

const DEFAULT_CONFIG: DocumentConfig = {
  logoEsquerda: '',
  logoCentro: '',
  logoDireita: '',
  logoEsquerdaTamanho: 64,
  logoCentroTamanho: 56,
  logoDireitaTamanho: 64,
  logoEsquerdaAtiva: true,
  logoCentroAtiva: true,
  logoDireitaAtiva: true,
  logoEsquerdaRedonda: false,
  logoCentroRedonda: false,
  logoDireitaRedonda: false,
  linha1: 'SECRETARIA MUNICIPAL DE SAÚDE DE ORIXIMINÁ',
  linha2: 'CAPS II',
  rodapeTexto: '',
  fonte: 'Arial',
  tamanhoFonte: 12,
  alinhamento: 'center',
  corTitulo: '#0c4a6e',
};

let _cachedConfig: DocumentConfig | null = null;
let _cacheTimestamp = 0;
const CACHE_TTL = 60_000; // 1 min

export async function loadDocumentConfig(): Promise<DocumentConfig> {
  if (_cachedConfig && Date.now() - _cacheTimestamp < CACHE_TTL) return _cachedConfig;
  try {
    const { data } = await supabase
      .from('system_config')
      .select('configuracoes')
      .eq('id', 'default')
      .maybeSingle();
    const cfg = (data?.configuracoes as any)?.config_impressao;
    if (cfg) {
      const cab = cfg.cabecalho || {};
      _cachedConfig = {
        logoEsquerda: cab.logoEsquerda || cab.logoUrl || '',
        logoCentro: cab.logoCentro || '',
        logoDireita: cab.logoDireita || '',
        logoEsquerdaTamanho: Number(cab.logoEsquerdaTamanho) || DEFAULT_CONFIG.logoEsquerdaTamanho,
        logoCentroTamanho: Number(cab.logoCentroTamanho) || DEFAULT_CONFIG.logoCentroTamanho,
        logoDireitaTamanho: Number(cab.logoDireitaTamanho) || DEFAULT_CONFIG.logoDireitaTamanho,
        logoEsquerdaAtiva: cab.logoEsquerdaAtiva !== false,
        logoCentroAtiva: cab.logoCentroAtiva !== false,
        logoDireitaAtiva: cab.logoDireitaAtiva !== false,
        logoEsquerdaRedonda: cab.logoEsquerdaRedonda === true,
        logoCentroRedonda: cab.logoCentroRedonda === true,
        logoDireitaRedonda: cab.logoDireitaRedonda === true,
        linha1: cab.linha1 || DEFAULT_CONFIG.linha1,
        linha2: cab.linha2 || DEFAULT_CONFIG.linha2,
        rodapeTexto: cfg.rodapeTexto || '',
        fonte: (cab.fonte && String(cab.fonte).trim()) || DEFAULT_CONFIG.fonte,
        tamanhoFonte: Number(cab.tamanhoFonte) > 0 ? Number(cab.tamanhoFonte) : DEFAULT_CONFIG.tamanhoFonte,
        alinhamento: (cab.alinhamento === 'left' || cab.alinhamento === 'right') ? cab.alinhamento : 'center',
        corTitulo: (cab.cor && String(cab.cor).trim()) || DEFAULT_CONFIG.corTitulo,
      };
    } else {
      _cachedConfig = { ...DEFAULT_CONFIG };
    }
  } catch {
    _cachedConfig = { ...DEFAULT_CONFIG };
  }
  _cacheTimestamp = Date.now();
  return _cachedConfig!;
}

export function invalidateDocumentConfigCache(): void {
  _cachedConfig = null;
  _cacheTimestamp = 0;
}

function resolveLogoUrl(configUrl: string, fallback: string): string {
  if (configUrl && configUrl.startsWith('http')) return configUrl;
  if (configUrl && configUrl.startsWith('/')) return configUrl;
  return fallback;
}

export interface InstitutionalLayoutOptions {
  pageSize?: 'A4' | 'A5';
  orientation?: 'portrait' | 'landscape';
  extraCSS?: string;
}

export function buildInstitutionalCSS(
  opts: InstitutionalLayoutOptions = {},
  config?: DocumentConfig,
): string {
  const size = opts.pageSize || 'A4';
  const orientation = opts.orientation || 'portrait';
  const cfg = config ?? DEFAULT_CONFIG;
  const fontFamily = `'${cfg.fonte.replace(/'/g, '')}', Arial, 'Helvetica Neue', Helvetica, sans-serif`;
  const baseSize = cfg.tamanhoFonte || 12; 
  const bodyPt = Math.max(9, Math.round(baseSize * 0.95 * 10) / 10); 
  const titlePt = Math.round((bodyPt + 2) * 10) / 10;
  const sectionPt = Math.round((bodyPt + 0.5) * 10) / 10;
  const smallPt = Math.max(8, Math.round((bodyPt - 1.5) * 10) / 10);
  const microPt = Math.max(7.5, Math.round((bodyPt - 2.5) * 10) / 10);
  const accent = cfg.corTitulo || '#0c4a6e';
  const headerAlign = cfg.alinhamento || 'center';
  return `
<style>
  @page {
    size: ${size} ${orientation};
    margin: 4mm 8mm 4mm 8mm;
  }
  @page :first {
    margin-top: 4mm;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  html, body { 
    font-family: ${fontFamily};
    width: 100%;
    background: #fff;
  }
  body {
    font-family: ${fontFamily};
    padding: 0;
    color: #000;
    font-size: ${bodyPt}pt;
    line-height: 1.1;
    background: #fff;
  }

  /* HEADER — institutional */
  .doc-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 0 1px 0;
    margin-bottom: 2px;
    border-bottom: 0.8px solid ${accent};
    position: relative;
  }

  .doc-header .logo-left,
  .doc-header .logo-right { flex-shrink: 0; }
  .doc-header .header-center {
    flex: 1;
    text-align: ${headerAlign};
    padding: 0 4px;
  }
  .doc-header h1 {
    font-size: ${titlePt - 2}pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.1px;
    color: ${accent};
    margin: 0;
    line-height: 1.0;
  }
  .doc-header .subtitle {
    font-size: ${bodyPt - 2.5}pt;
    color: #475569;
    margin-top: -1px;
    font-weight: 600;
  }
  .doc-header .doc-title {
    font-size: ${titlePt - 1}pt;
    font-weight: 700;
    margin-top: 1px;
    text-transform: uppercase;
    letter-spacing: 0.2px;
    color: #000;
    border-top: 0.5px solid #e2e8f0;
    padding-top: 1px;
    line-height: 1.0;
  }
  .doc-header .emit-date {
    font-size: ${microPt - 1}pt;
    color: #64748b;
    text-align: right;
    white-space: nowrap;
    position: absolute;
    right: 0;
    bottom: 0px;
  }

  /* META INFO BAR */
  .doc-meta {
    font-size: ${smallPt - 0.5}pt;
    color: #334155;
    padding: 2px 4px;
    background: #f8fafc;
    border: 0.5px solid #e2e8f0;
    border-radius: 2px;
    margin-bottom: 4px;
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    line-height: 1.0;
  }
  .doc-meta strong { color: #000; }

  /* CONTENT — justified */
  .doc-content {
    text-align: justify;
    text-justify: inter-word;
    font-size: ${bodyPt}pt;
    line-height: 1.15;
    word-break: break-word;
  }

  /* SUMMARY CARDS */
  .summary { display: flex; gap: 2px; margin-bottom: 4px; flex-wrap: wrap; }
  .stat { background: #f0f9ff; border: 0.5px solid #bae6fd; padding: 2px 6px; border-radius: 2px; text-align: center; min-width: 60px; }
  .stat strong { display: block; font-size: ${titlePt - 1}pt; color: ${accent}; }
  .stat small { font-size: ${microPt - 0.5}pt; color: #64748b; }

  /* SECTION TITLES */
  h2 {
    font-size: ${sectionPt - 0.5}pt;
    color: ${accent};
    margin: 3px 0 1px;
    padding-bottom: 0.2px;
    border-bottom: 0.5px solid #bae6fd;
    text-transform: uppercase;
    letter-spacing: 0.1px;
    font-weight: 700;
    break-after: avoid;
  }

  /* TABLES */
  table { width: 100%; border-collapse: collapse; margin-bottom: 2px; page-break-inside: auto; font-size: ${smallPt - 0.5}pt; }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  th, td { border: 0.5px solid #cbd5e1; padding: 2px 4px; text-align: left; font-size: ${smallPt - 0.5}pt; line-height: 1.05; }
  th { background: #f8fafc; font-weight: 700; color: #000; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

  /* FIELDS */
  .content-block { text-align: justify; text-justify: inter-word; font-size: ${bodyPt}pt; }
  .field { margin-bottom: 1px; }
  .field-label { font-size: ${microPt - 0.5}pt; text-transform: uppercase; color: #475569; font-weight: 700; letter-spacing: 0.1px; line-height: 1; }
  .field-value { font-size: ${bodyPt}pt; margin-top: 0; color: #000; line-height: 1.05; }

  /* SECTIONS (prontuário) */
  .section { margin-bottom: 1.5px; page-break-inside: avoid; break-inside: avoid; }
  .section-title { font-weight: 800; font-size: ${sectionPt - 1.5}pt; text-transform: uppercase; color: #1e293b; border-bottom: 0.4px solid #cbd5e1; padding-bottom: 0px; margin-bottom: 1px; line-height: 1; }
  .section-content { font-size: ${bodyPt}pt; line-height: 1.05; white-space: pre-wrap; min-height: 1px; text-align: justify; color: #000; overflow-wrap: break-word; }

  /* INFO GRID */
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 6px; margin-bottom: 3px; padding: 3px; background: #fff; border: 0.5px solid #000; border-radius: 0; }
  .info-label { font-weight: 700; font-size: ${microPt - 0.5}pt; text-transform: uppercase; color: #444; line-height: 1.0; }
  .info-value { font-size: ${bodyPt - 0.5}pt; color: #000; line-height: 1.0; font-weight: 500; }

  /* SIGNATURE */
  .signature { margin-top: 6px; text-align: center; page-break-inside: avoid; break-inside: avoid; width: 100%; display: flex; flex-direction: column; align-items: center; }
  .signature-line { width: 180px; border-top: 0.5px solid #000; margin: 0 auto 1px; }
  .signature .name { font-size: ${bodyPt - 0.5}pt; font-weight: 700; color: #000; line-height: 1.0; }
  .signature .role { font-size: ${smallPt - 1}pt; color: #475569; line-height: 1; }
  .signature .carimbo-container { margin-top: 4px; padding-top: 2px; }

  /* CARIMBO */
  .carimbo-digital { border: 1px solid #000; border-radius: 3px; padding: 4px 8px; text-align: center; font-size: ${smallPt - 1}pt; display: inline-block; background: #fff; line-height: 1.0; }
  .carimbo-digital .carimbo-nome { font-weight: 800; font-size: ${bodyPt - 1}pt; color: #000; text-transform: uppercase; }
  .carimbo-digital .carimbo-info { font-size: ${microPt - 1}pt; color: #334155; }

  /* FOOTER */
  .doc-footer {
    margin-top: 4px;
    padding-top: 1px;
    border-top: 0.5px solid ${accent};
    font-size: ${microPt - 1}pt;
    color: #64748b;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  @media print {
    body { 
      padding: 0 !important; 
      margin: 0 !important; 
      width: 100% !important; 
      color: #000 !important;
      background: transparent !important;
    }
    .doc-header { border-bottom-width: 0.5px !important; margin-bottom: 2px !important; padding-bottom: 1px !important; }
    .doc-header h1 { font-size: ${titlePt - 2.5}pt !important; line-height: 1.0 !important; }
    .doc-header .doc-title { font-size: ${titlePt - 1}pt !important; margin-top: 1px !important; padding-top: 1px !important; }
    .doc-header .subtitle { font-size: ${bodyPt - 2.5}pt !important; margin-top: -1px !important; }
    .doc-header img { max-height: 36px !important; width: auto !important; }
    .doc-meta { margin-bottom: 4px !important; padding: 2px 4px !important; font-size: ${smallPt - 1.5}pt !important; line-height: 1.0 !important; gap: 4px !important; }
    .section { margin-bottom: 2px !important; page-break-inside: avoid !important; }
    .section-title { font-size: ${sectionPt - 1.5}pt !important; padding-bottom: 0px !important; margin-bottom: 1px !important; }
    .info-grid { gap: 1.5px !important; padding: 2px !important; margin-bottom: 2px !important; border-width: 0.4px !important; }
    .no-print { display: none !important; }
    .signature { margin-top: 6px !important; }
    .doc-footer { margin-top: 4px !important; padding-top: 1px !important; font-size: ${microPt - 1.5}pt !important; }
  }
  @page {
    size: ${size} ${orientation};
    margin: 4mm 8mm 4mm 8mm !important;
  }
  @page :first {
    margin-top: 4mm !important;
  }

  ${opts.extraCSS || ''}
</style>`;
}

export const institutionalCSS = buildInstitutionalCSS();

export function docHeader(title: string, config: DocumentConfig, extraRight?: string): string {
  const clamp = (n: number, min = 28, max = 100) => Math.max(min, Math.min(max, n || 64));

  const showLeft = config.logoEsquerdaAtiva !== false;
  const showCenter = config.logoCentroAtiva !== false && !!(config.logoCentro && config.logoCentro.trim());
  const showRight = config.logoDireitaAtiva !== false;

  const leftUrl = showLeft ? resolveLogoUrl(config.logoEsquerda, logoSmsFallback) : '';
  const rightUrl = showRight ? resolveLogoUrl(config.logoDireita, logoCapsFallback) : '';
  const centerUrl = showCenter ? config.logoCentro : '';

  const hL = clamp(config.logoEsquerdaTamanho);
  const hC = clamp(config.logoCentroTamanho);
  const hR = clamp(config.logoDireitaTamanho);

  const now = new Date().toLocaleString('pt-BR');

  const roundStyle = (size: number, rounded: boolean) =>
    rounded
      ? `width:${size}px;height:${size}px;border-radius:9999px;object-fit:cover;background:#fff;`
      : `max-height:${size}px;max-width:${size * 2}px;width:auto;height:auto;object-fit:contain;`;

  const leftSlot = leftUrl
    ? `<div class="logo-left" style="flex:0 0 auto;min-width:${hL * 1.6}px;display:flex;justify-content:flex-start;">
         <img src="${leftUrl}" alt="Logo institucional esquerda" style="${roundStyle(hL, config.logoEsquerdaRedonda)}" onerror="this.style.display='none'" />
       </div>`
    : `<div class="logo-left" style="flex:0 0 auto;"></div>`;

  const rightSlot = rightUrl
    ? `<div class="logo-right" style="flex:0 0 auto;min-width:${hR * 1.6}px;display:flex;justify-content:flex-end;">
         <img src="${rightUrl}" alt="Logo institucional direita" style="${roundStyle(hR, config.logoDireitaRedonda)}" onerror="this.style.display='none'" />
       </div>`
    : (extraRight ? `<div class="logo-right" style="font-size:8pt;color:#64748b;">${extraRight}</div>` : `<div class="logo-right" style="flex:0 0 auto;"></div>`);

  const centerSlot = `
    <div class="header-center">
      <h1>${config.linha1}</h1>
      <div class="subtitle">${config.linha2}</div>
      ${centerUrl ? `<img src="${centerUrl}" style="${roundStyle(hC, config.logoCentroRedonda)};margin:2px auto;" />` : ''}
      <div class="doc-title">${title}</div>
    </div>
  `;

  return `
    <header class="doc-header">
      ${leftSlot}
      ${centerSlot}
      ${rightSlot}
      <div class="emit-date">Emitido em: ${now}</div>
    </header>
  `;
}

export function docFooter(config: DocumentConfig): string {
  const text = config.rodapeTexto || `© ${new Date().getFullYear()} ${config.linha1}`;
  return `
    <footer class="doc-footer">
      <div class="institution">${config.linha1}</div>
      <div class="footer-text">${text}</div>
      <div class="page-number"></div>
    </footer>
  `;
}

export async function openPrintDocument(title: string, body: string, meta: Record<string, string> = {}) {
  const config = await loadDocumentConfig();
  const css = buildInstitutionalCSS({}, config);
  const header = docHeader(title, config);
  const footer = docFooter(config);

  const metaHtml = Object.keys(meta).length > 0 
    ? `<div class="doc-meta">${Object.entries(meta).map(([k, v]) => `<span><strong>${k}:</strong> ${v}</span>`).join('')}</div>`
    : '';

  const fullHtml = `
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
      <meta charset="UTF-8">
      <title>${title}</title>
      ${css}
    </head>
    <body>
      <div class="document-container">
        ${header}
        ${metaHtml}
        <div class="doc-content">${body}</div>
        ${footer}
      </div>
      <script>
        window.onload = () => {
          setTimeout(() => {
            window.print();
            window.onafterprint = () => window.close();
          }, 300);
        };
      </script>
    </body>
    </html>
  `;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(fullHtml);
    win.document.close();
  }
}
