/**
 * Shared institutional print/PDF layout for SMS Oriximiná.
 * All documents generated by the system use this template
 * to ensure consistent branding across screen, PDF, and print.
 * 
 * Supports dual logos (SMS + CAPS II), justified text, proper
 * margins (2.5cm), 1.5 line spacing, Arial font.
 */

import { supabase } from '@/integrations/supabase/client';
import logoSmsFallback from '@/assets/logo-sms-oriximina.jpeg';
import logoCapsFallback from '@/assets/logo-caps-ii.png';

export interface DocumentConfig {
  logoEsquerda: string;
  logoCentro: string;
  logoDireita: string;
  logoEsquerdaTamanho: number;
  logoCentroTamanho: number;
  logoDireitaTamanho: number;
  logoEsquerdaAtiva: boolean;
  logoCentroAtiva: boolean;
  logoDireitaAtiva: boolean;
  /** Renderiza a logo como círculo (border-radius 9999px + object-fit cover). */
  logoEsquerdaRedonda: boolean;
  logoCentroRedonda: boolean;
  logoDireitaRedonda: boolean;
  linha1: string;
  linha2: string;
  rodapeTexto: string;
  /** Fonte base de todos os documentos (configurável). */
  fonte: string;
  /** Tamanho de fonte do corpo, em px (convertido para pt no CSS). */
  tamanhoFonte: number;
  /** Alinhamento do título institucional no cabeçalho. */
  alinhamento: 'left' | 'center' | 'right';
  /** Cor do título e das bordas institucionais (hex). */
  corTitulo: string;
}

const DEFAULT_CONFIG: DocumentConfig = {
  logoEsquerda: '',
  logoCentro: '',
  logoDireita: '',
  logoEsquerdaTamanho: 64,
  logoCentroTamanho: 56,
  logoDireitaTamanho: 64,
  logoEsquerdaAtiva: true,
  logoCentroAtiva: true,
  logoDireitaAtiva: true,
  logoEsquerdaRedonda: false,
  logoCentroRedonda: false,
  logoDireitaRedonda: false,
  linha1: 'SECRETARIA MUNICIPAL DE SAÚDE DE ORIXIMINÁ',
  linha2: 'CAPS II',
  rodapeTexto: '',
  fonte: 'Arial',
  tamanhoFonte: 12,
  alinhamento: 'center',
  corTitulo: '#0c4a6e',
};


let _cachedConfig: DocumentConfig | null = null;
let _cacheTimestamp = 0;
const CACHE_TTL = 60_000; // 1 min

export async function loadDocumentConfig(): Promise<DocumentConfig> {
  if (_cachedConfig && Date.now() - _cacheTimestamp < CACHE_TTL) return _cachedConfig;
  try {
    const { data } = await supabase
      .from('system_config')
      .select('configuracoes')
      .eq('id', 'default')
      .maybeSingle();
    const cfg = (data?.configuracoes as any)?.config_impressao;
    if (cfg) {
      const cab = cfg.cabecalho || {};
      _cachedConfig = {
        logoEsquerda: cab.logoEsquerda || cab.logoUrl || '',
        logoCentro: cab.logoCentro || '',
        logoDireita: cab.logoDireita || '',
        logoEsquerdaTamanho: Number(cab.logoEsquerdaTamanho) || DEFAULT_CONFIG.logoEsquerdaTamanho,
        logoCentroTamanho: Number(cab.logoCentroTamanho) || DEFAULT_CONFIG.logoCentroTamanho,
        logoDireitaTamanho: Number(cab.logoDireitaTamanho) || DEFAULT_CONFIG.logoDireitaTamanho,
        logoEsquerdaAtiva: cab.logoEsquerdaAtiva !== false,
        logoCentroAtiva: cab.logoCentroAtiva !== false,
        logoDireitaAtiva: cab.logoDireitaAtiva !== false,
        logoEsquerdaRedonda: cab.logoEsquerdaRedonda === true,
        logoCentroRedonda: cab.logoCentroRedonda === true,
        logoDireitaRedonda: cab.logoDireitaRedonda === true,
        linha1: cab.linha1 || DEFAULT_CONFIG.linha1,
        linha2: cab.linha2 || DEFAULT_CONFIG.linha2,
        rodapeTexto: cfg.rodapeTexto || '',
        fonte: (cab.fonte && String(cab.fonte).trim()) || DEFAULT_CONFIG.fonte,
        tamanhoFonte: Number(cab.tamanhoFonte) > 0 ? Number(cab.tamanhoFonte) : DEFAULT_CONFIG.tamanhoFonte,
        alinhamento: (cab.alinhamento === 'left' || cab.alinhamento === 'right') ? cab.alinhamento : 'center',
        corTitulo: (cab.cor && String(cab.cor).trim()) || DEFAULT_CONFIG.corTitulo,
      };
    } else {
      _cachedConfig = { ...DEFAULT_CONFIG };
    }
  } catch {
    _cachedConfig = { ...DEFAULT_CONFIG };
  }
  _cacheTimestamp = Date.now();
  return _cachedConfig!;
}

/** Invalidate cached config (call after saving new config) */
export function invalidateDocumentConfigCache(): void {
  _cachedConfig = null;
  _cacheTimestamp = 0;
}

function resolveLogoUrl(configUrl: string, fallback: string): string {
  if (configUrl && configUrl.startsWith('http')) return configUrl;
  if (configUrl && configUrl.startsWith('/')) return configUrl;
  // Use bundled fallback
  if (fallback.startsWith('http') || fallback.startsWith('/')) return fallback;
  return fallback;
}

/** Options for institutional layout (page size, orientation, extra CSS). */
export interface InstitutionalLayoutOptions {
  pageSize?: 'A4' | 'A5';
  orientation?: 'portrait' | 'landscape';
  /** Extra CSS appended after institutional rules (for document-specific styles). */
  extraCSS?: string;
}

/** Standard institutional CSS shared across all documents.
 *  When a `config` is provided, the user-customized font, font-size, alignment
 *  and accent color flow into the CSS so that every document reflects the
 *  values saved in "Configurações > Impressão e Documentos". */
export function buildInstitutionalCSS(
  opts: InstitutionalLayoutOptions = {},
  config?: DocumentConfig,
): string {
  const size = opts.pageSize || 'A4';
  const orientation = opts.orientation || 'portrait';
  const margin = size === 'A5' ? '12mm' : '25mm';
  const cfg = config ?? DEFAULT_CONFIG;
  const fontFamily = `'${cfg.fonte.replace(/'/g, '')}', Arial, 'Helvetica Neue', Helvetica, sans-serif`;
  // Painel salva em px; impressão usa pt → 1pt ≈ px * 0.75
  const bodyPt = Math.max(8, Math.round((cfg.tamanhoFonte || 12) * 0.75 * 10) / 10);
  const titlePt = Math.round((bodyPt + 1) * 10) / 10;
  const sectionPt = Math.round((bodyPt + 0.5) * 10) / 10;
  const smallPt = Math.max(7, Math.round((bodyPt - 1.5) * 10) / 10);
  const microPt = Math.max(6.5, Math.round((bodyPt - 2.5) * 10) / 10);
  const accent = cfg.corTitulo || '#0c4a6e';
  const headerAlign = cfg.alinhamento || 'center';
  return `
<style>
  @page {
    size: ${size} ${orientation};
    margin: 15mm 15mm 15mm 15mm;
  }
  @page :first {
    margin-top: 10mm;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  html, body { 
    font-family: ${fontFamily};
    width: 100%;
    height: 100%;
  }
  body {
    font-family: ${fontFamily};
    padding: 0;
    color: #000;
    font-size: ${bodyPt}pt;
    line-height: 1.3;
    background: #fff;
  }

  /* HEADER — institutional */
  .doc-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 0 6px 0;
    margin-bottom: 8px;
    border-bottom: 1.5px solid ${accent};
    position: relative;
  }
  .doc-header .logo-left,
  .doc-header .logo-right { flex-shrink: 0; }
  .doc-header .header-center {
    flex: 1;
    text-align: ${headerAlign};
    padding: 0 8px;
  }
  .doc-header h1 {
    font-size: ${titlePt - 1}pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.3px;
    color: ${accent};
    margin: 0;
    line-height: 1.1;
  }
  .doc-header .subtitle {
    font-size: ${bodyPt - 1}pt;
    color: #475569;
    margin-top: 1px;
    font-weight: 600;
  }
  .doc-header .doc-title {
    font-size: ${titlePt}pt;
    font-weight: 700;
    margin-top: 4px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #000;
    border-top: 1px solid #e2e8f0;
    padding-top: 3px;
  }
  .doc-header .emit-date {
    font-size: ${microPt}pt;
    color: #64748b;
    text-align: right;
    white-space: nowrap;
    position: absolute;
    right: 0;
    bottom: 2px;
  }

  /* META INFO BAR */
  .doc-meta {
    font-size: ${smallPt}pt;
    color: #334155;
    padding: 4px 8px;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 4px;
    margin-bottom: 10px;
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
    line-height: 1.2;
  }
  .doc-meta strong { color: #000; }

  /* CONTENT — justified; honor user font size */
  .doc-content {
    text-align: justify;
    text-justify: inter-word;
    font-size: ${bodyPt}pt;
    line-height: 1.4;
    word-break: break-word;
    hyphens: auto;
  }

  /* SUMMARY CARDS */
  .summary { display: flex; gap: 6px; margin-bottom: 12px; flex-wrap: wrap; }
  .stat { background: #f0f9ff; border: 1px solid #bae6fd; padding: 6px 12px; border-radius: 4px; text-align: center; min-width: 80px; }
  .stat strong { display: block; font-size: ${titlePt + 2}pt; color: ${accent}; }
  .stat small { font-size: ${microPt}pt; color: #64748b; }

  /* SECTION TITLES */
  h2 {
    font-size: ${sectionPt}pt;
    color: ${accent};
    margin: 10px 0 4px;
    padding-bottom: 2px;
    border-bottom: 1px solid #bae6fd;
    text-transform: uppercase;
    letter-spacing: 0.2px;
    font-weight: 700;
  }

  /* TABLES */
  table { width: 100%; border-collapse: collapse; margin-bottom: 12px; page-break-inside: auto; font-size: ${smallPt}pt; }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  th, td { border: 1px solid #d1d5db; padding: 5px 8px; text-align: left; font-size: ${smallPt}pt; }
  th { background: #f1f5f9; font-weight: 600; color: #1a1a1a; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  tr:nth-child(even) { background: #fafafa; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

  /* FIELDS */
  .content-block { text-align: justify; text-justify: inter-word; font-size: ${bodyPt}pt; }
  .field { margin-bottom: 8px; }
  .field-label { font-size: ${microPt}pt; text-transform: uppercase; color: #64748b; font-weight: 600; letter-spacing: 0.4px; }
  .field-value { font-size: ${bodyPt}pt; margin-top: 2px; color: #1a1a1a; }

  /* SECTIONS (prontuário) */
  .section { margin-bottom: 14px; page-break-inside: avoid; }
  .section-title { font-weight: 700; font-size: ${sectionPt}pt; text-transform: uppercase; color: ${accent}; border-bottom: 1.5px solid #bae6fd; padding-bottom: 4px; margin-bottom: 6px; }
  .section-content { font-size: ${bodyPt}pt; line-height: 1.55; white-space: pre-wrap; min-height: 16px; text-align: justify; color: #1e293b; }

  /* INFO GRID */
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 14px; padding: 10px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; }
  .info-label { font-weight: 600; font-size: ${microPt}pt; text-transform: uppercase; color: #64748b; }
  .info-value { font-size: ${bodyPt}pt; color: #1a1a1a; }

  /* QR AREA */
  .qr-area { text-align: center; margin-top: 24px; padding: 16px; border: 1px dashed #cbd5e1; border-radius: 6px; background: #fafafa; }
  .qr-area p { font-size: ${smallPt}pt; color: #64748b; }
  .qr-area .code { font-size: ${microPt}pt; color: #94a3b8; margin-top: 4px; font-family: monospace; }

  /* SIGNATURE */
  .signature { margin-top: 40px; text-align: center; }
  .signature-line { width: 280px; border-top: 1px solid #333; margin: 0 auto 6px; }
  .signature .name { font-size: ${bodyPt}pt; font-weight: 600; }
  .signature .role { font-size: ${smallPt}pt; color: #64748b; }

  /* DOCUMENT FOOTER: carimbo + assinatura */
  .doc-sign-footer { display: flex; justify-content: space-between; align-items: flex-end; margin-top: 32px; gap: 20px; }
  .doc-sign-footer .sign-block { flex: 1; }
  .doc-sign-footer .carimbo-block { text-align: right; }

  /* E-SIGNATURE */
  .e-signature-box {
    border: 1px solid #94a3b8; border-radius: 4px; padding: 8px 12px;
    font-size: ${microPt}pt; line-height: 1.5; color: #475569; max-width: 380px;
  }
  .e-signature-box .sig-title { font-weight: 700; font-size: ${smallPt}pt; color: ${accent}; margin-bottom: 4px; text-align: center; }
  .e-signature-box .sig-legal { font-size: ${Math.max(6, microPt - 0.5)}pt; color: #94a3b8; margin-top: 6px; font-style: italic; }

  /* CARIMBO */
  .carimbo-digital { border: 2px solid #1e293b; border-radius: 4px; padding: 8px 14px; text-align: center; font-size: ${smallPt}pt; display: inline-block; }
  .carimbo-digital .carimbo-nome { font-weight: 700; font-size: ${bodyPt}pt; }
  .carimbo-digital .carimbo-info { font-size: ${microPt}pt; color: #475569; }

  /* FOOTER */
  .doc-footer {
    margin-top: 24px;
    padding-top: 6px;
    border-top: 1.5px solid ${accent};
    font-size: ${microPt}pt;
    color: #64748b;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .doc-footer .institution { font-weight: 600; color: #334155; }

  /* PRINT MEDIA */
  @media print {
    body { padding: 0; }
    .doc-header { border-radius: 0; }
    .no-print { display: none !important; }
    nav, .sidebar, button, .toaster, [data-sonner-toaster] { display: none !important; }
    .doc-sign-footer { page-break-inside: avoid; }
    .e-signature-box { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  }
  ${opts.extraCSS || ''}
</style>`;
}

/** For backward compatibility */
export const institutionalCSS = buildInstitutionalCSS();

/**
 * Generate the standard document header HTML.
 * Supports up to three logos (left/center/right), each with independent size
 * (max-height in px) and enabled flag. Layout reorganizes automatically when
 * a logo is missing so there are no awkward gaps.
 */
export function docHeader(title: string, config: DocumentConfig, extraRight?: string): string {
  const clamp = (n: number, min = 28, max = 140) => Math.max(min, Math.min(max, n || 64));

  const showLeft = config.logoEsquerdaAtiva !== false;
  const showCenter = config.logoCentroAtiva !== false && !!(config.logoCentro && config.logoCentro.trim());
  const showRight = config.logoDireitaAtiva !== false;

  // Apply fallback ONLY when the slot is active and no URL is set.
  const leftUrl = showLeft ? resolveLogoUrl(config.logoEsquerda, logoSmsFallback) : '';
  const rightUrl = showRight ? resolveLogoUrl(config.logoDireita, logoCapsFallback) : '';
  const centerUrl = showCenter ? config.logoCentro : '';

  const hL = clamp(config.logoEsquerdaTamanho);
  const hC = clamp(config.logoCentroTamanho);
  const hR = clamp(config.logoDireitaTamanho);

  const now = new Date().toLocaleString('pt-BR');

  const roundStyle = (size: number, rounded: boolean) =>
    rounded
      ? `width:${size}px;height:${size}px;border-radius:9999px;object-fit:cover;background:#fff;`
      : `max-height:${size}px;max-width:${size * 2}px;width:auto;height:auto;object-fit:contain;`;

  const leftSlot = leftUrl
    ? `<div class="logo-left" style="flex:0 0 auto;min-width:${hL * 1.6}px;display:flex;justify-content:flex-start;">
         <img src="${leftUrl}" alt="Logo institucional esquerda" style="${roundStyle(hL, config.logoEsquerdaRedonda)}" onerror="this.style.display='none'" />
       </div>`
    : `<div class="logo-left" style="flex:0 0 auto;"></div>`;

  const rightSlot = rightUrl
    ? `<div class="logo-right" style="flex:0 0 auto;min-width:${hR * 1.6}px;display:flex;justify-content:flex-end;">
         <img src="${rightUrl}" alt="Logo institucional direita" style="${roundStyle(hR, config.logoDireitaRedonda)}" onerror="this.style.display='none'" />
       </div>`
    : `<div class="logo-right" style="flex:0 0 auto;"></div>`;

  const centerLogoHtml = centerUrl
    ? `<div class="logo-center" style="display:flex;justify-content:center;margin-bottom:6px;">
         <img src="${centerUrl}" alt="Logo institucional central" style="${roundStyle(hC, config.logoCentroRedonda)}" onerror="this.style.display='none'" />
       </div>`
    : '';

  const align = config.alinhamento || 'center';
  return `
    <div class="doc-header" style="position:relative;display:flex;align-items:center;justify-content:space-between;gap:12px;">
      ${leftSlot}
      <div class="header-center" style="flex:1;text-align:${align};">
        ${centerLogoHtml}
        <h1>${config.linha1}</h1>
        <div class="subtitle">${config.linha2}</div>
        <div class="doc-title">${title}</div>
      </div>
      ${rightSlot}
      <div class="emit-date">
        ${extraRight || ''}
        <div>Emitido em: ${now}</div>
      </div>
    </div>`;
}

/** Generate metadata bar */
export function docMeta(items: Record<string, string>): string {
  const entries = Object.entries(items).map(([k, v]) => `<strong>${k}:</strong> ${v}`).join(' &nbsp;|&nbsp; ');
  return `<div class="doc-meta">${entries}</div>`;
}

/** Generate the standard footer */
export function docFooter(config: DocumentConfig, extraInfo?: string): string {
  const now = new Date().toLocaleString('pt-BR');
  const rodape = config.rodapeTexto || '';
  return `
    <div class="doc-footer">
      <div class="institution">${config.linha1} — ${config.linha2}</div>
      <div>${rodape} ${extraInfo || ''}</div>
      <div>${now}</div>
    </div>
    <div style="text-align:center;font-size:7.5pt;color:#94a3b8;margin-top:4px;">
      Rua Barão do Rio Branco, S/N, Santa Terezinha, Oriximiná-PA, 68270-000
    </div>`;
}

/**
 * Open a print window with full institutional layout.
 * IMPORTANT: window.open MUST be called synchronously inside the user click
 * handler — otherwise the browser popup blocker silently kills the window.
 * We open the window first with a loading placeholder, then fetch the config
 * asynchronously and rewrite the document with the real content.
 * Throws if the popup is blocked so callers can show a toast.
 */
export async function openPrintDocument(
  title: string,
  body: string,
  meta?: Record<string, string>,
  options?: InstitutionalLayoutOptions,
): Promise<void> {
  // 1. Open window SYNCHRONOUSLY (preserves user-gesture trust)
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('POPUP_BLOCKED');
  }

  // 2. Write a friendly loading placeholder immediately
  try {
    printWindow.document.write(`<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>${title}…</title>
<style>body{font-family:Arial,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;color:#0369a1;font-size:14px;}</style>
</head><body>Gerando documento…</body></html>`);
  } catch { /* ignore */ }

  // 3. Now fetch config (async) and rewrite the doc
  const config = await loadDocumentConfig();
  const metaHtml = meta ? docMeta(meta) : '';
  const css = buildInstitutionalCSS(options, config);

  try {
    printWindow.document.open();
    printWindow.document.write(`<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <title>${title} — ${config.linha1}</title>
  ${css}
</head>
<body>
  ${docHeader(title, config)}
  ${metaHtml}
  <div class="doc-content">
    ${body}
  </div>
  ${docFooter(config)}
</body>
</html>`);
    printWindow.document.close();
    setTimeout(() => {
      try { printWindow.focus(); printWindow.print(); } catch { /* ignore */ }
    }, 400);
  } catch (err) {
    try { printWindow.close(); } catch { /* ignore */ }
    throw err;
  }
}
